# Generated by Django 5.1.1 on 2024-09-21 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanction',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
