# Generated by Django 5.1.1 on 2024-09-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_test_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='pdf',
            field=models.FileField(default=1, upload_to='media/pdf'),
            preserve_default=False,
        ),
    ]
