# Generated by Django 5.1.1 on 2024-09-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sanction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanction',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sanction',
            name='shakl1',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
