# Generated by Django 5.1.1 on 2024-09-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_test_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='pdf',
            field=models.FileField(upload_to='pdf/'),
        ),
    ]
