# Generated by Django 5.1.1 on 2024-09-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sanction_region_sanction_shakl1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanction',
            name='title',
        ),
    ]
