# Generated by Django 5.1.1 on 2024-09-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_sanction_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanction',
            name='hackType',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
