# Generated by Django 5.1.1 on 2024-09-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_test_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='logo',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdf/'),
        ),
    ]
