# Generated by Django 5.1.1 on 2024-09-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sanctioniib_rename_sanction_sanctionoper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SanctionIIB',
        ),
    ]
