# Generated by Django 5.1.1 on 2024-09-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sanctioniib'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SanctionIIB',
        ),
    ]
