# Generated by Django 5.1.1 on 2024-10-01 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_sanctioniib'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionProkuratura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('region', models.CharField(max_length=50, null=True)),
                ('hackType', models.CharField(max_length=50, null=True)),
                ('shakl1', models.CharField(max_length=10, null=True)),
                ('pdf', models.FileField(null=True, upload_to='pdf/prokuratura/')),
            ],
        ),
        migrations.AddField(
            model_name='sanctioniib',
            name='hackType',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
