# Generated by Django 5.1.1 on 2024-10-02 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sanctionprokuratura_sanctioniib_hacktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('hackType', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=50, null=True)),
                ('shakl1', models.CharField(max_length=10, null=True)),
                ('pdf', models.FileField(null=True, upload_to='pdf/')),
            ],
        ),
    ]
