# Generated by Django 5.1.3 on 2024-11-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_sanctionstar_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanctioniib',
            name='pdf_2',
            field=models.FileField(null=True, upload_to='pdf/iib/'),
        ),
        migrations.AddField(
            model_name='sanctionoper',
            name='pdf_2',
            field=models.FileField(null=True, upload_to='pdf/'),
        ),
        migrations.AddField(
            model_name='sanctionprokuratura',
            name='pdf_2',
            field=models.FileField(null=True, upload_to='pdf/prokuratura/'),
        ),
    ]
