# Generated by Django 5.1.3 on 2024-11-27 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_sanctioniib_pdf_2_sanctionoper_pdf_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionSigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('hackType', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=50, null=True)),
                ('shakl1', models.CharField(max_length=10, null=True)),
                ('pdf', models.FileField(null=True, upload_to='pdf/')),
            ],
        ),
        migrations.RemoveField(
            model_name='sanctioniib',
            name='pdf_2',
        ),
        migrations.RemoveField(
            model_name='sanctionoper',
            name='pdf_2',
        ),
        migrations.RemoveField(
            model_name='sanctionprokuratura',
            name='pdf_2',
        ),
    ]
